-- Migration 014: state_of_play on topics (IC7 — topic-level "state of play" header)
--
-- Stores the grounded status block rendered at the top of the topic view:
--   { "situation": "...", "threads": [ {label,status,note}, ... ], "generated_at": "..." }
-- Regenerated by the pipeline ONLY when a state_change fact lands (architecture §7.4),
-- so it's cheap (~1 LLM call) and never recursively rewritten.
--
-- Safe on existing rows: NULL means "no state-of-play yet" → the UI simply hides the block.
-- The pipeline write degrades to a no-op if this migration hasn't been applied.

ALTER TABLE topics
    ADD COLUMN IF NOT EXISTS state_of_play           jsonb       DEFAULT NULL;

ALTER TABLE topics
    ADD COLUMN IF NOT EXISTS state_of_play_updated_at timestamptz DEFAULT NULL;
